import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-white dark:bg-slate-800 mt-8 py-4 shadow-inner">
      <div className="container mx-auto px-4 md:px-8 text-center">
        <p className="text-sm text-slate-500 dark:text-slate-400">
          Generated by Google Gemini. Data may not be fully accurate or complete.
        </p>
      </div>
    </footer>
  );
};

export default Footer;
